import random

albums = [
    "Whatever People say I Am, That's What I'am Not (Artic monkeys)",
    "Abbey Road (The Beatles)",
    "Renaissance (Beyoncé)",
    "Happier Than ever ( Billie Eilish)",
    "Ants From Up There (Black Country New Road)",
    "22, a million (Bon Iver)",
    "IRIDESCENCE (Brockhampton)",
    "El Madrileño (C.Tangana)",
    "Twin Fantasy (Car Seat Headrest)",
    "Alive 2007 (Daft punk)",
    "The Rise And Fall Of Ziggy Stardust And The Spiders From Mars (David Bowie)",
    "Post Mortem (Dillom)",
    "I Love You, Honeybear (Father John Misty)",
    "Rumours (Fleetwood Mac)",
    "Hi This Is Flume (Flume)",
    "BLONDE (Frank Ocean)",
    "Maggot Brain (Funkadelic)",
    "Plastic Beach (Gorillaz )",
    "Assume Form (James Blake)",
    "NECTAR (Joji )",
    "The Life of Pablo (Kanye West)",
    "To Pimp a Butterfly (Kendrick)",
    "In the Court of the Crimson King (Kim Crimson)",
    "Sound Of Silver (LCD Soundsystem)",
    "Hybrid Theory (Linkin Park)",
    "Melodrama (Lorde)",
    "Cleopatra (The lumineers)",
    "Circles (Mac Miller )",
    "Madvillainy (Mf Doom )",
    "The Miseducation of Lauryn Hill (Ms. Lauryn Hill)",
    "The Black Parade (My Chemical Romance)",
    "De Todas Las Flores (Natalia Lafourcade)",
    "Wish You Were Here (Pink Floyd)",
    "Punisher (Phoebe Bridgers)",
    "In Rainbows (Radiohead)",
    "Apricot Princess (Rex Orange County)",
    "SAWAYAMA (Rina Sawayama)",
    "MOTOMAMI (Rosalia)",
    "Process (Sampha)",
    "La Grasa de las Capitales (Serú Girán)" "Marchita (Silvana Estrada)",
    "Toxicity (System of a Down)",
    "Stop Making Sense (Talking Heads)",
    "RODEO (Travis SCOTT )",
    "Is This It (The Strokes)",
    "Folklore (Taylor Swift)",
    "The Low End Theory (A Tribe Called Quest)",
    "Trench (Twenty One Pilots)",
    "IGOR (Tyler The creator )",
    "Wallsocket (Underscores)",
    "Titanic Rising (Weyes Blood)",
]

indice_aleatorio = random.randint(0, len(albums) - 1)
print(f"El album aleatorio de hoy es: {albums[indice_aleatorio]}")